### ISSUE TITLE
Shop schema 🏪

### ISSUE THREAD

**Issue by Code42Cate** [lokabees/api#1]
### This issue is supposed to track the discussing around the shop schema:

[Initial commit and relevant file](https://github.com/lokabees/api/commit/a4f8e1f5c8c5c8de5a937c711c2b0799fc9da4c9)

#### Questions: 
- How do we want to save and validate contact information?
- Does someone have a better idea how we can implement [opening hours](https://github.com/getitsocial/getit_api/blob/2819e2148f3aedbe6fe0bd28abfd15b4167328c3/src/api/shop/model.js#L244)? 
- How do we want to save the image URLs?
- Do we actually need company type (gbr, gmbh etc) and employee count?! @tguelcan 
- How do we save delivery options? Enum+Array or booleans?

#### Todos:
- [x] Remove content field (everything will break)
- [x] Add geoJSON field [(should get added by a pre save hook if the locationId changed)](https://github.com/getitsocial/getit_api/blob/2819e2148f3aedbe6fe0bd28abfd15b4167328c3/src/api/shop/model.js#L163)
- [x] Add hook to request and save address data from the here API if the locationId changed 
- [x] Add [displayPosition](https://github.com/getitsocial/getit_api/blob/2819e2148f3aedbe6fe0bd28abfd15b4167328c3/src/api/shop/model.js#L233) and [address.display](https://github.com/getitsocial/getit_api/blob/2819e2148f3aedbe6fe0bd28abfd15b4167328c3/src/api/shop/model.js#L240) virtuals
- [x] [Add shopname-slug-thingy](https://github.com/getitsocial/getit_api/blob/2819e2148f3aedbe6fe0bd28abfd15b4167328c3/src/api/shop/model.js#L40)

And probably 500 other things that I forgot?:D @cnasenberg
